question_data = [
        {"type": "boolean",
         "difficulty": "easy",
         "category": "Animals",
         "question": "Rabbits are rodents.",
         "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
         "question": "Jingle Bells was originally meant for Thanksgiving", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
                                           "question": "The Xenomorph from the science fiction film &quot;Alien&quot; has acidic blood.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
         "question": "Furby was released in 1998.", "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "hard", "category": "Science &amp; Nature",
         "question": "The chemical element Lithium is named after the country of Lithuania.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Television",
         "question": "Bob Ross was a US Air Force pilot.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
         "question": "Pink Guy&#039;s debut album was &quot;Pink Season&quot;.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "History",
                                          "question": "If you grab the bladed end of a longsword in a specific way, you will not cut yourself.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
         "question": "Brandon Routh plays the titular character in the movie &quot;John Wick&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
         "question": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.",
         "correct_answer": "True", "incorrect_answers": ["False"]}
    ]
